export const LOGIN_ID = `AKfycbwUtPOQt1yjbH0hjKEICyWCoLQXmIsyAAZ6gxYBGMUCe5XKhCOQBFQ61xqgPg7s8txabQ`;
export const STEPS_ID = `AKfycbxf65c3mCPm5Z2kMqvfZnFBFRw3WOCTB9OT89PEgxCCPMI-lPcCfvn3-5eJxdBBx_W_`;
